/**
 * Core type definitions for the Async Digest application.
 * These types define the data structures used throughout the processing pipeline.
 */

// =============================================================================
// Input Types
// =============================================================================

/**
 * Normalized entry format - the common internal representation for all inputs.
 * All Slack messages and Loom content are converted to this format before processing.
 */
export interface NormalizedEntry {
  source: "slack" | "loom";
  author: string;
  timestamp: string; // ISO 8601 format
  content: string;
}

/**
 * Parsed link information extracted from user input.
 */
export interface ParsedLink {
  type: "slack" | "loom";
  url: string;
  identifier: string; // Thread ID, video ID, etc.
}

// =============================================================================
// Output Types - Digest Structure
// =============================================================================

/**
 * A single decision extracted from the discussion.
 */
export interface Decision {
  description: string;
  context: string; // Brief context about how/why this decision was made
  participants: string[]; // Who was involved in making this decision
}

/**
 * An action item extracted from the discussion.
 */
export interface ActionItem {
  action: string;
  owner: string | null; // null if owner was not mentioned/detectable
  status: "decided" | "pending" | "blocked";
  context?: string; // Optional context about the action item
}

/**
 * A single event in the discussion timeline.
 */
export interface TimelineEvent {
  timestamp: string;
  summary: string; // Condensed description of what happened at this point
  participants: string[];
  significance: "low" | "medium" | "high"; // How significant this moment was
}

/**
 * A topic cluster identified in the discussion.
 */
export interface TopicCluster {
  topic: string;
  entries: number; // Number of entries in this cluster
  summary: string;
}

/**
 * The complete digest output structure.
 * This is the final output generated by the AI processing pipeline.
 */
export interface Digest {
  /** High-level summary of the discussion */
  executiveSummary: {
    whatWasDiscussed: string;
    whyItMatters: string;
    whatChanged: string;
  };

  /** Condensed chronological view of how the discussion evolved */
  timeline: TimelineEvent[];

  /** Decisions organized by status */
  decisions: {
    decided: Decision[];
    pending: Decision[];
    blocked: Decision[];
  };

  /** Extracted action items */
  actionItems: ActionItem[];

  /** Things still unresolved */
  openQuestions: string[];

  /** Topics/themes identified in the discussion */
  topicClusters: TopicCluster[];

  /** Detected disagreements or conflicting viewpoints */
  disagreements: string[];

  /** Repeated feedback patterns */
  repeatedFeedback: string[];
}

// =============================================================================
// API Types
// =============================================================================

/**
 * Request body for the /api/generate endpoint.
 */
export interface GenerateRequest {
  links: string[];
}

/**
 * Response from the /api/generate endpoint.
 */
export interface GenerateResponse {
  success: boolean;
  digest?: Digest;
  error?: string;
  /** Indicates whether real AI or mock AI was used */
  aiMode: "openai" | "mock";
}

// =============================================================================
// Processing Types
// =============================================================================

/**
 * Result from the link parsing step.
 */
export interface LinkParseResult {
  valid: ParsedLink[];
  invalid: string[];
}

/**
 * Configuration for the AI processor.
 */
export interface AIProcessorConfig {
  useRealAI: boolean;
  openAIApiKey?: string;
}
